// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://xynqqakrebmhwkahvlgp.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bnFxYWtyZWJtaHdrYWh2bGdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MDg0MDMsImV4cCI6MjA0ODI4NDQwM30.sCdSQcWi9g7nGQlyNhzmqCg-okoz2itzGOoDYNMMLO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);